umapp/urls.py
from django.urls import path
from .views import *


app_name = "umapp"
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", SignupView.as_view(), name="signup"),
    path("private/", ContactView.as_view(), name="contact"),
    path("article/", ArticleCreateView.as_view(), name="articlecreate"),
    path("articlelist/", ArticleListView.as_view(), name="articlelist"),
    path("article/<int:pk>/detail/",
         ArticleDetailView.as_view(), name="articledetail"),
    path("article/<int:pk>/update/",
         ArticleUpdateView.as_view(), name='articleupdate'),
    path("article/<art_id>/comment",
         CommentCreateView.as_view(), name='commentcreate'),
    path("ajax_check_username/", AjaxCheckUsernameView.as_view(),
         name='ajaxcheckusername'),


    path('api/v1/article-list/', ArticleListAPIView.as_view(), name="articlelistapi"),




]

umproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("umapp.urls")),
    path('summernote/', include('django_summernote.urls')),

]
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

umapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Article(models.Model):
    title = models.CharField(max_length=500)
    image = models.ImageField(upload_to='images')
    content = models.TextField()
    views = models.PositiveIntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Comment(models.Model):
    commentor = models.ForeignKey(User, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.commentor.username

umapp/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget
from .models import *
from django.contrib.auth.models import User



class LoginForm(forms.Form):
	username=forms.CharField(widget=forms.TextInput(attrs={
		"class":"form-control",
		"autocomplete":"off",
		"placeholder":"Enter Username"
		}))
	password=forms.CharField(widget=forms.PasswordInput(attrs={
		'class':"form-control",
		"autocomplete":"off",
		"placeholder":"Enter password"
		}))


class SignupForm(forms.Form):
	username=forms.CharField(widget=forms.TextInput(attrs={
		"class":"form-control",
		"autocomplete":"off",
		"placeholder":"Enter Username"
		}))
	email=forms.EmailField(widget=forms.EmailInput(attrs={
		"class":"form-control",
		"autocomplete":"off",
		"placeholder":"Enter email"
		}))
	password=forms.CharField(widget=forms.PasswordInput(attrs={
		"class":"form-control",
		"autocomplete":"off",
		"placeholder":"Enter Password"
		}))
	confirm_password=forms.CharField(widget=forms.PasswordInput(attrs={
		"class":"form-control",
		"autocomplete":"off",
		"placeholder":"Enter Password"
		}))


	def clean_username(self):
		uname=self.cleaned_data['username']
		if User.objects.filter(username=uname).exists():
			raise forms.ValidationError("Username is already exist")

		
		return uname



	def clean_confirm_password(self):
		pw=self.cleaned_data['password']
		c_pw=self.cleaned_data['confirm_password']
		if (pw !=c_pw):
			raise forms.ValidationError("Password did not match.")

		if (len(pw)<6):
			raise forms.ValidationError("Password too short")

		numbers = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
		c = 0
		for i in c_pw:
			if i in numbers:
				c += 1
		if c < 1:
			raise forms.ValidationError("must include a number")


		return c_pw



class ArticleForm(forms.ModelForm):
	class Meta:
		model=Article
		fields=['title', 'image','content'] #exclude=["views",'author']
		widgets = {
			'content': SummernoteWidget()
		}



class CommentForm(forms.ModelForm):
	class Meta:
		model=Comment
		fields=['text']
		widgets={
		"text":forms.Textarea(attrs={
			"class":"form-control",
			"placeholder":'Enter any comment',
			"rows":2
			})
		}

umapp/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.views.generic import *
from .models import *
from .forms import *
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse, reverse_lazy
from django.http import JsonResponse


class LoginRequiredMixin(object):
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            pass
        else:
            return redirect("umapp:login")

        return super().dispatch(request, *args, **kwargs)


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = "home.html"


class LoginView(FormView):
    template_name = "login.html"
    form_class = LoginForm
    success_url = "/"

    def form_valid(self, form):
        x = form.cleaned_data["username"]
        y = form.cleaned_data["password"]
        # print(x,y)
        usr = authenticate(username=x, password=y)
        # print(usr)
        if usr is not None:
            login(self.request, usr)

        else:
            return render(self.request, 'login.html',
                          {
                              "error": "Invalid Credential",
                              "form": form
                          })

        return super().form_valid(form)

    def get_success_url(self):

        if self.request.user.is_superuser:
            return "/"
        else:
            return "/private/"


class LogoutView(View):
    def get(self, request):
        logout(request)

        return redirect('/')


class SignupView(FormView):
    template_name = "signup.html"
    form_class = SignupForm
    success_url = "/"

    def form_valid(self, form):
        x = form.cleaned_data["username"]
        e = form.cleaned_data["email"]
        y = form.cleaned_data["password"]

        usr = User.objects.create_user(x, e, y)
        login(self.request, usr)

        return super().form_valid(form)


class ContactView(TemplateView):
    template_name = "contact.html"


class ArticleCreateView(LoginRequiredMixin, CreateView):
    template_name = 'articlecreate.html'
    form_class = ArticleForm
    success_url = reverse_lazy('umapp:home')

    def form_valid(self, form):
        author = self.request.user
        form.instance.author = author

        return super().form_valid(form)


class ArticleListView(ListView):
    template_name = "articlelist.html"
    queryset = Article.objects.all().order_by("-id")
    context_object_name = "allarticles"


class ArticleDetailView(DetailView):
    template_name = "articledetail.html"
    model = Article
    context_object_name = "articleobject"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["abc"] = CommentForm

        return context


class ArticleUpdateView(UpdateView):
    template_name = "articlecreate.html"
    form_class = ArticleForm
    success_url = "/articlelist/"
    model = Article
    queryset = Article.objects.all()


class CommentCreateView(LoginRequiredMixin, CreateView):
    template_name = 'commentcreate.html'
    form_class = CommentForm
    success_url = reverse_lazy('umapp:articlelist')

    def form_valid(self, form):
        art_id = self.kwargs['art_id']
        artobj = Article.objects.get(id=art_id)
        author = self.request.user
        form.instance.article = artobj
        form.instance.commentor = author

        return super().form_valid(form)

    def get_success_url(self):
        article_id = self.kwargs["art_id"]

        return reverse("umapp:articledetail", kwargs={"pk": article_id})


class AjaxCheckUsernameView(View):
    def get(self, request, *args, **kwargs):
        u = request.GET['username']
        if User.objects.filter(username=u).exists():
            message = "unavailable"

        else:
            message = "available"

        return JsonResponse({
            "message": message
        })


from rest_framework.generics import ListAPIView
from .serializers import *


class ArticleListAPIView(ListAPIView):
    serializer_class = ArticleSerializer
    queryset = Article.objects.order_by('-id')

templates/articlecreate.html
{% extends 'base.html' %}


{% block title %}Create{% endblock %}


{% block content %}
	<div class="row">
	<div class="col-md-4 mx-auto">
		<h3>
			<u><b>Blog Creation</b></u>
		</h3>
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{form.as_p}}
			<button class="btn btn-info">Submit</button>
			
			
		</form>
		
	</div>
	
</div>	

{% endblock %}

templates/articledetail.html
{% extends 'base.html' %}


{% block title %}Article-Detail{% endblock %}


{% block content %}
<a href="/articlelist/"><button>Back</button></a>
<h2>{{articleobject.title}}</h2>
<img src="{{articleobject.image.url}}" class="img-fluid"  style="height: 200px; object-fit: cover" >
<p>{{articleobject.content|safe}}</p>
<p>Published on:<b>{{articleobject.date}}</b></p>
<hr>
<b><p>Author:{{articleobject.author}}</p></b>
<!-- <a href="{% url 'umapp:commentcreate' articleobject.id %}">Comment</a>	 -->
<div class="row">
	<div class="col-md-6">
		<form method="POST" action="{% url 'umapp:commentcreate' articleobject.id %}">
	{% csrf_token %}
	<!-- {{abc.as_p}} -->
	{{abc.text}}
	<button>Comment</button>
	
	
</form>
	</div>
</div>

<h3>All Comments:</h3>
<hr>
{% for cmt in articleobject.comment_set.all|dictsortreversed:'id' %}
<li>{{cmt.text}} by <b>{{cmt.commentor}} </b> {{cmt.date|timesince}} ago</li>
{% endfor %}




{% endblock %}

templates/articlelist.html
{% extends 'base.html' %}


{% block title %}Articles{% endblock %}


{% block content %}
<h2>All Articles</h2>
{% for i in allarticles %}
<b><li><a href="{% url 'umapp:articledetail' i.pk %}">{{i.title}}</a><button><a href="/article/{{i.id}}/update/">	Update</a></button></li></b>
<img src="{{i.image.url}}" class="img-fluid"  style="height: 200px; object-fit: cover">
<b><p>{{i.date}}</p></b><hr>
<p>Written By:{{i.author}}</p>
{% endfor %}


{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
	<!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	 -->
	<title>
		{% block title %}
		{% endblock %}
	</title>
  <style>
    /* Dropdown Button */
/*.dropbtn {
  background-color: #4CAF50;
  color: white;
  padding: 16px;
  font-size: 16px;
  border: none;
}
*/
/* The container <div> - needed to position the dropdown content */
.dropdown {
  position: relative;
  display: inline-block;
}

/* Dropdown Content (Hidden by Default) */
.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f1f1f1;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

/* Links inside the dropdown */
/*.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}
*/
/* Change color of dropdown links on hover */
.dropdown-content a:hover {background-color: #ddd;}

/* Show the dropdown menu on hover */
.dropdown:hover .dropdown-content {display: block;}

/* Change the background color of the dropdown button when the dropdown content is shown */
.dropdown:hover .dropbtn {background-color: #3e8e41;}
  </style>
</head>
<body class="container">
	<!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{request.user}}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'umapp:logout' %}">Logout</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav> -->
	<!-- <a href="/">Home</a>| -->
<a href="{% url 'umapp:home' %}">Home</a>|
  <div class="dropdown">
    {% if request.user.is_authenticated %}
  <button class="dropbtn">  {{request.user}} </button>
  <div class="dropdown-content">
    <a href="#">  <a href="{% url 'umapp:logout' %}">Logout</a></a>
    {% else %}

  <a href="{% url 'umapp:login' %}">Login</a>|
  <a href="{% url 'umapp:signup' %}">Sign UP</a>|
  {% endif %}

  </div>
</div>
  <a href="{% url 'umapp:contact' %}">Contact</a>|
  <a href="{% url 'umapp:articlecreate' %}">Create Article</a>|
  <a href="{% url 'umapp:articlelist' %}">Article List</a>|
	
	

	
	
	<hr>


	{% block content %}


	{% endblock %}
<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
  
  {% block js %}

  {% endblock %}
</body>
</html>

templates/commentcreate.html
{% extends 'base.html' %}



{% block title %}comment{% endblock %}


{% block content %}
<form method="POST">
	{% csrf_token %}
	{{form.as_p}}
	<button>Comment</button>
	
	
</form>


{% endblock %}

templates/contact.html
{% extends 'base.html' %}


{% block title %}contact{% endblock %}


{% block content %}
		<h3>this is content of protected contact page</h3>


{% endblock %}

templates/home.html
{% extends 'base.html' %}


{% block title %}
       	Home
		{% endblock %}


{% block content %}
		<h3>this is content of home page</h3>


{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %}
       	Login
		{% endblock %}


{% block content %}
<div class="row">
	<div class="col-md-4 mx-auto">
		<h3>
			<u><b>Login Form</b></u>
		</h3>
		<form method="POST">
			{% csrf_token %}
			{{form.as_p}}
			<button class="btn btn-info">Submit</button>
			<span class="text-danger">
				{{error}}
			</span>
			
		</form>
		
	</div>
	
</div>


{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block title %}
       	Signup
		{% endblock %}


{% block content %}
<div class="row">
	<div class="col-md-4 mx-auto">
		<h3>
			<u><b>SignUp Form</b></u>
		</h3>
		<p id="error" style="color:red"></p>
		<form method="POST">
			{% csrf_token %}
			{{form.as_p}}
			<button class="btn btn-info" id="btn">Submit</button>
			<span class="text-danger">
				{{error}}
			</span>
			
		</form>
		
	</div>
	
</div>
<p id="mdv"></p>

{% endblock %}

{% block js %}

<script >
$(document).ready(function(){
	$("#id_username").on("keyup",function(){
		var uname=$(this).val();
		$.ajax({
			url:"/ajax_check_username/",
			data:{
				"username":uname
			},
			success:function(data){
				
				// $("#mdv").text(data.message);
				if (data.message=="unavailable"){
					$("#error").text("Username is already exist.");
					$("#btn").attr("disabled","true")

				}
				else{
					$("#error").text("");
					$("#btn").removeAttr("disabled")



				}
			}
		})


	})
})	


</script>
{% endblock %}